### ISSUE TITLE
mvn error

### ISSUE THREAD

**Issue by hustlrr** [neo4j/neo4j-documentation#80]
I try to build this project by : mvn clean install, but I got the following error:
![image](https://cloud.githubusercontent.com/assets/6689218/25985926/c59f7c8e-371f-11e7-9da9-295731d8ce99.png)
how should I solve this problem?

**Comment by jjaderberg** [comment]
Try building [neo4j/neo4j](https://github.com/neo4j/neo4j/) so that you have those artifacts installed locally. Running `mvn install -DskipTests -T2C` or similar on your clone of that repository is a reasonable way to do it. Make sure to build the branch corresponding to the one you are working on for this repository.

An alternative is to set the version of this project to something that is released to Maven Central, as mentioned [in the README](https://github.com/neo4j/neo4j-documentation#local-pipeline). For example, use `versions:set -DnewVersion=3.2.0` to set the version for building against newly released `3.2.0`.

I'll look into the error--possibly it is related to Maven cleaning snapshot artifacts when a release is made. We just released `3.2.0`, so `3.2.0-SNAPSHOT` artifacts would then have been dropped. That's not so nice, so I'll see what we can do to remedy it.

Thanks for reporting.

**Comment by jjaderberg** [comment]
@hustlrr Now that there are snapshot artifacts for 3.2.1 we have bumped the version (https://github.com/neo4j/neo4j-documentation/commit/1d6757e0285a48209f99ab9e22f99fb8915ece28), and I also made the snapshot repository explicit for resolving plugins (https://github.com/neo4j/neo4j-documentation/commit/80b9d08c10760237b982df5be8e1b74ea4a32e0c). Between these you should now be able to build this project without building any dependencies, and without setting a released version.
